# SPDX-FileCopyrightText: 2025 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

name: Mirror GitLab repository

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  mirror-gitlab-repo:
    uses: veloren/.github/.github/workflows/mirror.yml@main
    with:
      repository-url: ${{ github.repositoryUrl }}
      token: ${{ secrets.MIRROR_TOKEN_GITHUB }}
      rewrite-lfs: true
